apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-deployment
  namespace: kubernetesapp
  labels:
    app: kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
        - name: kube
          image: suntribe2020/kubernetes:0.0.1
          imagePullPolicy: IfNotPresent